sudo: true

language: java

services:
  - docker

jdk:
  - openjdk11

install: true

script:
  - docker network create etlNwis

  - |
    docker \
    run \
    --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$TRAVIS_BUILD_DIR":/usr/src/mymaven \
    -w /usr/src/mymaven \
    --network=etlNwis \
    -e TESTING_DATABASE_PORT=5432 \
    -e TESTING_DATABASE_ADDRESS=wqpDatabase \
    -e TESTING_DATABASE_NETWORK=etlNwis \
    -e MYSQL_DATABASE_ADDRESS=nwiswebDatabase \
    -e MYSQL_DATABASE_PORT=3306 \
    maven:3.6.0-jdk-11 mvn clean verify

  - docker network rm etlNwis

after_success:
  - bash <(curl -s https://codecov.io/bash)
